---
- name: 
  hosts: 192.168.1.98
  remote_user: root  
      
  tasks: 
    - name: 
      apt: 
        name: git 
        state: present
    - name:
      apt: 
        name: nodejs
        state: present 
    - name:
      apt: 
        name: npm
        state: present
    - name: 
      git:
        repo: 
        dest: 
                
...